/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team.margarita.streamit;

/**
 * Lets the user change his password
 * 
 * @author Thomas Van Raemdonck
 */
public class LoginChange extends javax.swing.JFrame {

    /**
     * Creates new form LoginChange
     */
    public LoginChange() {
        initComponents();
        lblEmailFalse.setVisible(false);
        lblPassCurFalse.setVisible(false);
        lblPassNewFalse.setVisible(false);
        lblFouteGegevens.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNewPass = new javax.swing.JPasswordField();
        txtCurPass = new javax.swing.JPasswordField();
        buttonChange = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblEmailFalse = new javax.swing.JLabel();
        lblPassCurFalse = new javax.swing.JLabel();
        lblPassNewFalse = new javax.swing.JLabel();
        lblFouteGegevens = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Emailaddress");

        jLabel2.setText("Enter current password");

        jLabel3.setText("Enter new password");

        buttonChange.setText("Change");
        buttonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        lblEmailFalse.setForeground(new java.awt.Color(153, 0, 0));
        lblEmailFalse.setText("Email cannot be empty!");

        lblPassCurFalse.setForeground(new java.awt.Color(153, 0, 51));
        lblPassCurFalse.setText("Current password cannot be empty");

        lblPassNewFalse.setForeground(new java.awt.Color(153, 0, 51));
        lblPassNewFalse.setText("New password cannot be empty");

        lblFouteGegevens.setForeground(new java.awt.Color(153, 0, 51));
        lblFouteGegevens.setText("Foute gegevens");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmailFalse)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEmail)
                                        .addComponent(txtCurPass, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                    .addComponent(lblPassCurFalse)
                                    .addComponent(lblPassNewFalse)
                                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblFouteGegevens, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonChange)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCancel)))
                        .addGap(114, 114, 114))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmailFalse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lblPassCurFalse)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCurPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassNewFalse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonChange)
                    .addComponent(lblFouteGegevens))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * check if all fields are correct and send the new data
     * 
     * @param evt 
     */
    private void buttonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeActionPerformed
        String email = txtEmail.getText();
        String currentPassword = txtCurPass.getText();
        String newPassword = txtNewPass.getText();
        if (email.equalsIgnoreCase("")) {
            lblEmailFalse.setVisible(true);
        }
        else {
            lblEmailFalse.setVisible(false);
        }
        if(currentPassword.equalsIgnoreCase("")) {
            lblPassCurFalse.setVisible(true);
        }
        else {
            lblPassCurFalse.setVisible(false);
        }
        if(newPassword.equalsIgnoreCase("")) {
            lblPassNewFalse.setVisible(true);
        }
        else {
            lblPassNewFalse.setVisible(false);
        }
        if(!email.equalsIgnoreCase("") && !currentPassword.equalsIgnoreCase("") && !newPassword.equalsIgnoreCase("")) {
            checkLogin(email,currentPassword,newPassword);
        }
        
    }//GEN-LAST:event_buttonChangeActionPerformed

    /**
     * cancel the password change
     * 
     * @param evt 
     */
    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        new UserLogin().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed
    
    /**
     * complete the password change
     * 
     * @param email
     * @param pwd
     * @param newPas 
     */
    private void checkLogin(String email, String pwd,String newPas) {
        boolean login = UserRequest.changePass(email, pwd, newPas);
        if (login) {
            lblFouteGegevens.setVisible(false);
            new UserLogin().setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        else {
            lblFouteGegevens.setVisible(true);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonChange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEmailFalse;
    private javax.swing.JLabel lblFouteGegevens;
    private javax.swing.JLabel lblPassCurFalse;
    private javax.swing.JLabel lblPassNewFalse;
    private javax.swing.JPasswordField txtCurPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtNewPass;
    // End of variables declaration//GEN-END:variables
}
